version: '3'

includes:
  blackjacker:
    taskfile: ./blackjacker/Taskfile.yaml
    dir: ./blackjacker
    flatten: true
  strategy:
    taskfile: ./tools/strategy/Taskfile.yaml
    dir: ./tools/strategy
